name: Release on tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'

jobs:
  release-gerber-files:
    runs-on: ubuntu-latest
    steps:
    - name: Tag name
      id: tag_name
      run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
    - name: Trigger Release
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Release
        ref: "${{ github.ref }}"
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{ "ref": "${{ steps.tag_name.outputs.TAG }}" }'
